pipeline
{

    agent {
        label 'Dev'
    }

    stages
    {
        stage('Build')
        {
            steps
            {
              sh 'mvn clean package'
            }
            post {
                success {
                    archiveArtifacts artifacts: '**/target/*.war'
                
                }
            }
        }
        
    } 
}